Add Generalized Envy Graph algorithm
Teamable-Analytics/algorithms pull request #140
Opened 2023-10-12 16:35 UTC by ketphan02

Added new algorithm with the new algo configs

2023-10-12 16:36 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +import math
Add algorithm pseudocode at top

2023-10-12 16:40 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +            # allocation_C = pi(i) if i not in C else pi(i_j+1) if i == i_j in C
```suggestion
```

2023-10-12 16:40 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +                    # Find the student with the lowest utility in the cycle
```suggestion
```

2023-10-12 16:40 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +
```suggestion
```

2023-10-12 16:40 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +            print("-----")
Use the new save method

2023-10-12 16:52 UTC, ketphan02 commented
Add documentation of algorithm to Latex

2023-10-13 04:07 UTC, Opeyem1a requested changes

2023-10-13 04:07 UTC, Opeyem1a commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +class EnvyGraph:
each algorithm gets its own directory so you really don't have to crunch every class and util function into this one file, it feels kinda messy to me

2023-10-13 04:07 UTC, Opeyem1a commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +if __name__ == "__main__":
same comment as with MRR - why is this here?

2023-10-13 04:07 UTC, Opeyem1a commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +    def _get_N_plus(self, projects: List[Project], student: Student) -> List[Project]:
I'm guessing you named these functions/variables in a way that aligns with the formulas in the papers you read, but remember this is code that someone else will read, and some of these function/variable names make kinda no sense.

I see a few options:
1. Keep wacky function names, add better comments
2. Make better function names, add comments to explain what they correlate to in the papers
3. ??? be creative

2023-10-13 04:07 UTC, Opeyem1a commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +        This run in O(1)
nit;

Do we really need to annotate every function with its big-O? What value do these add as comments?

2023-10-13 04:07 UTC, Opeyem1a commented on api/ai/new/interfaces/algorithm_options.py
> +class GeneralizedEnvyGraphAlgorithmOptions(AlgorithmOptions):
new algorithms should be added to the AlgorithmType enum

2023-10-17 00:19 UTC, ketphan02 commented on api/ai/new/geg_algorithm/geg_algorithm.py
> +
Algo not completed

2023-11-10 06:16 UTC, Opeyem1a requested changes

2023-11-13 05:03 UTC, ketphan02 commented on api/ai/new/geg_algorithm/utils.py
> +    utilities: Dict[Tuple[int, int], int] = {}
I agree, I was doing this so I could remove the check if project id exists, but it turns nasty real quick

2023-11-14 01:15 UTC, Opeyem1a approved these changes
LGTM

2023-11-14 01:21 UTC, Opeyem1a commented
Current dependencies on/for this PR:
* main
  * **PR #140** <a href="https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/140?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/140?utm_source=stack-comment).

2023-11-14 01:22 UTC, merged