Add api validation: algorithm_generation_options
Teamable-Analytics/algorithms pull request #203
Opened 2023-11-07 07:55 UTC by ketphan02

Part 2 of #201

2023-11-07 08:05 UTC, ketphan02 commented
Reminder: change base to `main` before merge

2023-11-08 04:59 UTC, Opeyem1a requested changes

2023-11-08 04:59 UTC, Opeyem1a commented on api/ai/new/interfaces/algorithm_options.py
> +        return Schema({"algorithm_type": Const(AlgorithmType.RANDOM.value)})
it's BRUTAL that we have to put the algorithm type in the schema even though it's not in the dataclass, if we can avoid this it would be sick

2023-11-08 04:59 UTC, Opeyem1a commented on api/ai/new/interfaces/algorithm_options.py
> +                SchemaOptional("attributes_to_diversify"): Optional[List[int]],
why optional list int?

2023-11-08 04:59 UTC, Opeyem1a commented on api/ai/new/interfaces/algorithm_options.py
> +                "algorithm_type": Const(AlgorithmType.PRIORITY_NEW.value),
use PRIORITY here, i'm gonna get rid of PRIORITY_NEW

2023-11-08 04:59 UTC, Opeyem1a commented on api/ai/new/priority_algorithm/priority/priority.py
> +            if student.attributes is not None:
student.attributes should never be None, if it is, something massive is wrong and we *want* it to throw an error

2023-11-08 04:59 UTC, Opeyem1a commented on tests/test_api/test_validators/test_generate_teams_validator/test_generate_teams_validator.py
> +    def test_errors__algorithm_options__weight_algorithm(self):
idk if I like this naming scheme, I think the "test_{name of function}__{explain test briefly}" is a better idea here still

2023-11-10 06:17 UTC, Opeyem1a commented on tests/test_api/test_validators/test_generate_teams_validator/test_generate_teams_validator.py
> +    def test_errors__algorithm_options__weight_algorithm(self):
kind of a nitpick but also I think we should have test names just give context on what the problem is without having to read the whole test

2023-11-14 04:50 UTC, Opeyem1a requested changes
some more small things to remove

2023-11-14 04:50 UTC, Opeyem1a commented on api/ai/priority_algorithm/priority/priority.py
> +            if student.attributes is None:
it's never None, this should be impossible and if it happens, I want it to throw an error

2023-11-14 04:50 UTC, Opeyem1a commented on api/api/validators/generate_teams_validator.py
> +        # TODO: Do not commit this
prolly dont commit this

2023-11-14 05:35 UTC, Opeyem1a approved these changes
lgtm

2023-11-14 05:36 UTC, merged