Fix API production refuses to handle localhost
Teamable-Analytics/algorithms pull request #316
Opened 2023-12-26 13:38 UTC by ketphan02

2023-12-28 16:21 UTC, Opeyem1a requested changes

2023-12-28 16:21 UTC, Opeyem1a commented on api/api/settings/prod.py
> +CORS_ALLOW_ALL_ORIGINS = True
On prod?

2023-12-28 16:22 UTC, Opeyem1a requested changes

2023-12-28 16:22 UTC, Opeyem1a commented on requirements.txt
> +bcrypt==4.1.2
also why?

2024-01-10 07:03 UTC, ketphan02 commented on api/api/settings/prod.py
> +CORS_ALLOW_ALL_ORIGINS = True
Yes, since this is public API

2024-01-10 07:05 UTC, ketphan02 commented on requirements.txt
> +bcrypt==4.1.2
I save the encrypted key as a password, therefore, even when the key is leaked (not likely), it is less likely to exploit our service

2024-01-15 11:13 UTC, Opeyem1a approved these changes

2024-01-16 17:57 UTC, merged