Add COSC341 W2021T2 student and team provider
Teamable-Analytics/algorithms pull request #318
Opened 2023-12-27 03:44 UTC by justino599

Closes #311

2023-12-27 03:45 UTC, justino599 commented on benchmarking/data/real_data/cosc341_w2022_provider/data_parser.py
Do we want to include this file in the repo?

2023-12-27 03:46 UTC, justino599 commented on benchmarking/data/real_data/cosc341_w2022_provider/gen_group_set-20220331_141058.json
Same with this file, do we keep it in?

2023-12-28 18:00 UTC, Opeyem1a requested changes

2024-01-06 12:15 UTC, Opeyem1a approved these changes
gucci

2024-01-06 19:20 UTC, merged