API for student generation
Teamable-Analytics/algorithms pull request #365
Opened 2024-02-20 08:57 UTC by ketphan02

2024-02-20 20:29 UTC, Opeyem1a requested changes

2024-02-20 20:29 UTC, Opeyem1a commented on api/api/views/generate_class.py
> +                number_of_students=int(request_data["class_size"]),
nit;
use .get even if no default imo

2024-02-20 20:29 UTC, Opeyem1a commented on api/api/views/generate_class.py
> +                        (int(k), float(v)) for k, v in value_dict.items()
why float(v) here (remind me, I might just be forgetting)

2024-02-20 20:29 UTC, ketphan02 commented on api/api/views/generate_class.py
> +                number_of_students=int(request_data["class_size"]),
Doing this so it will throw KeyError

2024-02-20 20:31 UTC, ketphan02 commented on benchmarking/data/simulated_data/mock_student_provider.py
> +            if range_config[0][0] is not None and isinstance(
True

2024-02-25 04:53 UTC, Opeyem1a requested changes

2024-02-25 04:53 UTC, Opeyem1a commented on api/api/urls/__init__.py
> +    r"create", CreateClassCompositionViewSet, basename="create_class_composition"
endpoint name suggestion -> "simulate people"

2024-02-25 04:53 UTC, Opeyem1a commented on api/api/urls/__init__.py
> +    r"create", CreateClassCompositionViewSet, basename="create_class_composition"
like it would be `simulate/people` to use this endpoint, in general called `simulate` and in the view called `people`

2024-02-25 04:53 UTC, Opeyem1a commented on benchmarking/data/simulated_data/mock_student_provider.py
> +        if not is_unique(list(self.attribute_ranges.keys())):
Wait but it's an object? Like a hashmap? If you set 2 keys as the same it would have overwritten it, no?

2024-02-25 04:53 UTC, Opeyem1a commented on benchmarking/data/simulated_data/mock_student_provider.py
> +        if self.number_of_enemies > self.number_of_students:
it's a problem even if it's equal to

2024-02-25 04:53 UTC, Opeyem1a commented on benchmarking/data/simulated_data/mock_student_provider.py
> +        if self.number_of_friends > self.number_of_students:
it's a problem even if it's equal to

2024-02-26 01:07 UTC, Opeyem1a approved these changes

2024-02-26 01:30 UTC, merged