Implement Path-GASP
Teamable-Analytics/algorithms pull request #71
Opened 2023-09-20 18:35 UTC by ketphan02

### Issue
- We want to benchmark the algorithms from Jeff's thesis
- For now, I choose one of the most naive algorithm: **Path-GASP**

### Changes
- Added a new field for `MockStudentProvider`: `project_list` to get all projects
- Added a new generation method to generate project preferences for all students in `MockStudentProvider`
- Added new algorithm under `benchmarking/other_algorithms/path_gasp.py`

2023-09-21 05:07 UTC, Opeyem1a reviewed
I think we should meet at some point to discuss this, I kinda dislike this approach on an architectural level and there is a misconception or two about some of the existing stuff (I think)

2023-09-21 05:07 UTC, Opeyem1a requested changes
For now though, I don't think we should merge this as is

2023-09-27 20:13 UTC, ketphan02 commented on benchmarking/data/simulated_data/mock_student_provider.py
> +                preferences=preferences,
You're right! Then should we remove preferences field in Student?

2023-10-17 00:23 UTC, ketphan02 commented
We do not need Path-GASP since it's too slow and too naive

2023-10-17 00:23 UTC, closed without merging