add CLI to runs
Teamable-Analytics/algorithms pull request #82
Opened 2023-09-24 05:56 UTC by Opeyem1a

2023-09-24 05:56 UTC, Opeyem1a commented
Current dependencies on/for this PR:
* main
  * **PR #82** <a href="https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/82" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/82?utm_source=stack-comment).

2023-09-24 20:28 UTC, Hedgemon4 requested changes

2023-09-24 20:28 UTC, Hedgemon4 commented on benchmarking/runs/concentrate_many_attributes.py
> +def concentrate_many_attributes(num_trials: int = 10):
Do you not need to surround the function call here with `typer.run(concentrate_many_attributes)` as you did in the previous file?

2023-09-25 15:40 UTC, Hedgemon4 approved these changes
LGTM

2023-09-25 17:18 UTC, justino599 approved these changes
lgtm

2023-09-25 17:20 UTC, merged